### ISSUE TITLE
Dead code in wfqueue.c

### ISSUE THREAD

**Issue by raphaelcohn** [chaoran/hpc-queue#6]
Hi,

I'm trying out a conversion of the `wfqueue.c` to Rust. The following line of code in `enq_slow()` seems to be partly dead `if (CAS(&enq->id, &id, -i)) id = -i;`. The CAS is still needed, I think, but the Rust compiler has identified that the store to `id` is never needed. Cursory examination of the code following the do-while loop would indeed suggest that is the case, as `id` is always written to.

Of course, the compiler could be wrong...

**Comment by raphaelcohn** [comment]
FYI, this is a separate effort to crossbeam - I'm investigating the implications of using persistent memory (eg Non-Volatile DIMMS)...

**Comment by chaoran** [comment]
@raphaelcohn You're right. the `id = -i` assignment is not needed. It is redundant because of line https://github.com/chaoran/fast-wait-free-queue/blob/aad89011445e0ac496b4702679826180ff16af7c/wfqueue.c#L182

I think I probably put it there to hint the compiler to cache the value of `id` in register.
